# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('team_name', models.CharField(max_length=30)),
                ('robot_weight', models.FloatField()),
                ('robot_height', models.IntegerField()),
                ('team_location', models.CharField(max_length=30)),
                ('team_notes', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
