# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frcstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventname',
            table='event_name',
        ),
        migrations.AlterModelTable(
            name='matchnumber',
            table='match_number',
        ),
        migrations.AlterModelTable(
            name='week',
            table='weeks',
        ),
    ]
