# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frcstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_number',
            field=models.PositiveIntegerField(),
        ),
    ]
