# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frcstats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.IntegerField(max_length=50)),
                ('event_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'weeks',
            },
        ),
        migrations.AddField(
            model_name='event_name',
            name='week_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frcstats.Week'),
        ),
    ]
