# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frcstats', '0002_auto_20160212_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auton_high_goals', models.IntegerField()),
                ('auton_low_goals', models.IntegerField()),
                ('auton_def_crossed', models.CharField(max_length=15)),
                ('auton_def_reached', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'matchstats',
            },
        ),
        migrations.CreateModel(
            name='MatchNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeleopModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teleop_high_goals', models.IntegerField()),
                ('teleop_low_goals', models.IntegerField()),
                ('teleop_def_crossed', models.CharField(max_length=15)),
                ('teleop_def_stuck', models.CharField(max_length=15)),
                ('hang_input', models.IntegerField()),
                ('def_played', models.IntegerField()),
            ],
            options={
                'db_table': 'matchstats',
            },
        ),
        migrations.AlterField(
            model_name='event_name',
            name='event_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterModelTable(
            name='week',
            table=None,
        ),
    ]
