# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frcstats', '0002_auto_20160225_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivetrain', models.CharField(max_length=20)),
                ('gear_reduc', models.CharField(max_length=20)),
                ('motors', models.CharField(max_length=20)),
                ('extra_notes', models.CharField(max_length=120)),
                ('team_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frcstats.Team')),
            ],
            options={
                'db_table': 'robot_info',
            },
        ),
    ]
