# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frcstats', '0003_drive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsByEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('event_name', models.CharField(max_length=50)),
                ('shorthand', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'teams_by_event',
            },
        ),
        migrations.AlterField(
            model_name='match',
            name='teleop_cdf',
            field=models.IntegerField(choices=[(3, b'crossed twice'), (2, b'crossed once'), (4, b'did not cross'), (1, b'got stuck'), (0, b'not in play')], default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='teleop_drawb',
            field=models.IntegerField(choices=[(3, b'crossed twice'), (2, b'crossed once'), (4, b'did not cross'), (1, b'got stuck'), (0, b'not in play')], default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='teleop_lowbar',
            field=models.IntegerField(choices=[(3, b'crossed twice'), (2, b'crossed once'), (4, b'did not cross'), (1, b'got stuck'), (0, b'not in play')], default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='teleop_moat',
            field=models.IntegerField(choices=[(3, b'crossed twice'), (2, b'crossed once'), (4, b'did not cross'), (1, b'got stuck'), (0, b'not in play')], default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='teleop_portc',
            field=models.IntegerField(choices=[(3, b'crossed twice'), (2, b'crossed once'), (4, b'did not cross'), (1, b'got stuck'), (0, b'not in play')], default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='teleop_ramparts',
            field=models.IntegerField(choices=[(3, b'crossed twice'), (2, b'crossed once'), (4, b'did not cross'), (1, b'got stuck'), (0, b'not in play')], default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='teleop_rockwall',
            field=models.IntegerField(choices=[(3, b'crossed twice'), (2, b'crossed once'), (4, b'did not cross'), (1, b'got stuck'), (0, b'not in play')], default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='teleop_rought',
            field=models.IntegerField(choices=[(3, b'crossed twice'), (2, b'crossed once'), (4, b'did not cross'), (1, b'got stuck'), (0, b'not in play')], default=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='teleop_sallyp',
            field=models.IntegerField(choices=[(3, b'crossed twice'), (2, b'crossed once'), (4, b'did not cross'), (1, b'got stuck'), (0, b'not in play')], default=None),
        ),
    ]
