# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frcstats', '0003_auto_20160214_0028'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autonmodel',
            table='matchstats_auto',
        ),
        migrations.AlterModelTable(
            name='teleopmodel',
            table='matchstats_teleop',
        ),
    ]
