# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frcstats', '0004_auto_20160228_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='shorthand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frcstats.TeamsByEvent'),
            preserve_default=False,
        ),
    ]
